{
    'name': 'Student Management',
    'version': '1.0',
    'author': 'Generated by ChatGPT',
    'website': 'https://example.com',
    'category': 'Education',
    'summary': 'Simple Student Management (Odoo 18 compatible)',
    'description': 'Demo Student Management module with list/form/search and basic security.',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/student_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
